# ---------------------------------------------------------------
# âš  æ³¨æ„ï¼
# ---------------------------------------------------------------
# Hexo æœ‰ä¸¤ä¸ªé…ç½®æ–‡ä»¶ï¼Œåˆ†åˆ«ä¸ºä½äºç«™ç‚¹æ ¹ç›®å½•çš„ã€Œç«™ç‚¹é…ç½®æ–‡ä»¶ã€å’Œæ­¤å¤„çš„ã€Œä¸»é¢˜é…ç½®æ–‡ä»¶ã€
# ä¿®æ”¹æ—¶æ³¨æ„å¯¹åº”é…ç½®æ–‡ä»¶ï¼Œéƒ¨åˆ†ä¸»é¢˜é…ç½®æ–‡ä»¶çš„å†…å®¹å¯èƒ½éœ€è¦å¤åˆ¶åˆ°ç«™ç‚¹é…ç½®æ–‡ä»¶æ‰èƒ½ç”Ÿæ•ˆ



# ---------------------------------------------------------------
# <head> æ ‡ç­¾é…ç½®
# ---------------------------------------------------------------

head: 
  
  # ç½‘ç«™å›¾æ ‡
  favicon:
    ico: 
    small: /img/ico.png
    medium: /img/ico.png
    apple_touch_icon: /img/ico.png
    safari_pinned_tab: /img/ico.png
  
  # ç¤¾äº¤åˆ†äº«é“¾æ¥
  opengraph: 
    enable: true
    type: 
    twitter_card: summary_large_image
    twitter_id: 
    twitter_site: 
    image: page.thumbnail
    fb_admins: 
    fb_app_id: 

  # è‡ªå®šä¹‰ head
  custom_head: 
    # - ''
    # - ''



# ---------------------------------------------------------------
# å¯¼èˆªæ /å°é¢é…ç½®
# ---------------------------------------------------------------

# é¡¶éƒ¨å¯¼èˆªæ è®¾ç½®
navbar: 

  # å·¦ä¾§åç§°æ˜¾ç¤º
  sitename: é˜¿è´¤çš„å°ç ´ç«™
  
  # å³ä¾§ç«™å†…å¯¼èˆªé“¾æ¥
  menu: 
    - name: é¦–é¡µ
      url: /
    - name: æ ‡ç­¾
      url: /tags/
    - name: å½’æ¡£
      url: /archives/
    - name: å‹é“¾
      url: /friends/
    - name: Page
      url: /page/
    - name: æ—¶å…‰æœº
      url: /artitalk/
  # å¯¼èˆªæ æ°¸è¿œæ˜¾ç¤ºåœ¨å±å¹•é¡¶ç«¯
  # ä»…å½“å±å¹•å®½åº¦ä¸å°äº 1080 px æ—¶ç”Ÿæ•ˆ
  sticky: false

# å°é¢ cover è®¾ç½®
cover: 

  # æ˜¾ç¤ºåœ¨æœ€ä¸Šæ–¹ cover å¤„çš„ç«™ç‚¹åç§°
  sitename: é˜¿è´¤å“¦ğŸ˜

  # è‹¥ avatar é…ç½®ä¸ä¸ºç©ºï¼Œåˆ™ä¼˜å…ˆä½¿ç”¨ avatar è¦†ç›– sitename
  avatar: 
  
  # sitename/avatar ä¸‹æ–¹çš„ä¸€å¥è¯ä»‹ç»
  description: ä½ å¥½ï¼Œæ¬¢è¿æ¥åˆ°æˆ‘çš„å°ç ´ç«™ã€‚ğŸ˜˜



# ---------------------------------------------------------------
# æ ·å¼è‡ªå®šä¹‰
# ---------------------------------------------------------------

style: 

  # é¢œè‰²é…ç½®
  color: 
    main_color: '#2e3033'

  # å¼§åº¦è®¾ç½®
  radius: 
    main_radius: 30px
    
  # é—´è·è®¾ç½®
  space: 
    main_space: 2rem
    sm_space: 1.5rem  # å½“å±å¹•å®½åº¦å°äº 650px æ—¶å€™å¯ç”¨


  # é»˜è®¤ä»£ç é«˜äº®
  highlight: 

    # é»˜è®¤ä»£ç é«˜äº®ä¸»é¢˜
    default: 

    # æš—è‰²ä»£ç é«˜äº®ä¸»é¢˜
    darkmode: 

  # highlight.js ä»£ç é«˜äº®
  hljs: 

    # é»˜è®¤ä»£ç é«˜äº®ä¸»é¢˜
    default: 

    # æš—è‰²ä»£ç é«˜äº®ä¸»é¢˜
    darkmode: 

  # prismjs ä»£ç é«˜äº®
  prismjs: 

    # é»˜è®¤ä»£ç é«˜äº®ä¸»é¢˜
    default: 

    # æš—è‰²ä»£ç é«˜äº®ä¸»é¢˜
    darkmode: 



# ---------------------------------------------------------------
# meta åº“
# ---------------------------------------------------------------

meta:

  # é»˜è®¤æ–‡ç« æ ‡é¢˜
  title: 'no title'
  
  # é»˜è®¤æ–‡ç« ä½œè€…ï¼ˆå¯åœ¨front-matterä¸­è¦†ç›–ï¼‰
  author:
    name: é˜¿è´¤
    url: https://chralpha.com
  
  # æ–‡ç« åˆ›å»ºæ—¥æœŸ
  date:
    title: ''
    format: 'YYYY-MM-DD' # æ—¥æœŸæ ¼å¼ http://momentjs.com/docs/
  
  # æ–‡ç« æ›´æ–°æ—¥æœŸ
  updated:
    title: ''
    format: 'YYYY-MM-DD' # æ—¥æœŸæ ¼å¼ http://momentjs.com/docs/

  # æ–‡ç« ç¼©ç•¥å›¾
  thumbnail: 
    enable: true
    default:   # é»˜è®¤ç¼©ç•¥å›¾ï¼Œå½“é¡µé¢ `thumbnail` å­—æ®µä¸ºç©ºæ—¶ fallback è‡³æ­¤å‚æ•°

  # æ–‡ç« è¿‡æ—¶æé†’
  expire: 
    enable: false
    duration: 120  # è¶…è¿‡æ­¤å¤©æ•°åˆ™æ˜¾ç¤ºè¿‡æœŸæé†’

  # æ–‡ç« è‡ªåŠ¨æ‘˜è¦
  auto_excerpt: 
    enable: false
    length: 150

  # æ–‡ç« ç›®å½•
  toc: 
    enable: false
    list_number: false

  # æ–‡ç« ç‰ˆæƒå£°æ˜
  copyright: 
    enable: false
    
    # åœ¨ä½œè€…å£°æ˜å’Œæ°¸ä¹…é“¾æ¥ä¹‹åï¼Œå¯ä»¥å¤šè¡Œï¼Œæ”¯æŒ markdown
    custom_text:
      # - ''
      # - ''



# ---------------------------------------------------------------
# è¯„è®ºç³»ç»Ÿ
# ---------------------------------------------------------------

comments: 
  use:   # disqus | disqusjs | valine | minivaline | gitalk | gitment | levere | changyan | wildfire

  # Disqus
  disqus:  
    shortname: 

  # DisqusJS  
  disqusjs: 
    shortname: 
    siteName: 
    api: 
    apikey: 
    admin: ''
    nesting: 2

  # Valine
  valine: 
    appId: 
    appKey:
    placeholder: 
    path: 
    avatar: 
    meta: [nick, mail, link]
    pageSize: 
    lang: 
    visitor: 
    highlight: 
    avatarForce: 
    recordIP: 
    serverURLs: 
    enableQQ: 
    requiredFields: [nick, mail]
    emojiCDN: 
    emojiMaps: 

  # MiniValine
  minivaline:  
    appId: 
    appKey: 
    mode: 
    placeholder: 
    pathname: 
    adminEmailMd5: 
    master: 
    friends: 
    tagMeta: 
    math: 
    md: 
    lang: 
    emoticonUrl:
    NoRecordIP: 
    maxNest: 
    pageSize: 
    enableQQ: 
    visitor: 
    serverURLs: 

  # Gitalk
  gitalk:
    repo:
    owner:
    clientID:
    clientSecret:

  # Gitment
  gitment:
    repo:
    owner:
    client_id:
    client_secret:

  # Artalk
  artalk: 
    serverUrl: 
    placeholder: 
    noComment: 
    defaultAvatar: 
    pageKey: 
    gravatar: 
      cdn: 
    readMore: 
      pageSize: 
      autoLoad: 
    emoticons: 
  
  # Livere æ¥æ¯”åŠ›
  livere: 
    livere_uid:

  # ç•…è¨€
  changyan: 
    appid:
    conf:
    thread_key_type: path # id | pathï¼Œå•ç‹¬å®šä¹‰æ—¶å€™ç”¨ â€œidâ€

  # Wildfire
  wildfire: 
    database_provider: firebase # firebase | wilddog
    wilddog_site_id:
    firebase_api_key:
    firebase_auth_domain:
    firebase_database_url:
    firebase_project_id:
    firebase_storage_bucket:
    firebase_messaging_sender_id:
    theme: light # light | dark
    locale: en
    
  # Twikoo
  twikoo:
    envId: # ä½ çš„ CloudBase ç¯å¢ƒ ID



# ---------------------------------------------------------------
# ç»Ÿè®¡æœåŠ¡
# ---------------------------------------------------------------

analytics:
  google_site_id:
  gtags_site_id:
  baidu_site_id: 
  cnzz_site_id: 
  cloudflare_site_id: 



# ---------------------------------------------------------------
# ç½‘ç«™é¡µè„š
# ---------------------------------------------------------------

footer:
  
  # è®¾ç½®ç«™ç‚¹èµ·å§‹æ—¶é—´ï¼Œç”¨äºåº•éƒ¨ copyright æ˜¾ç¤º
  # ä¾‹å¦‚ï¼šå°†æ­¤è®¾ä¸º `2018`ï¼Œé‚£ä¹ˆé¡µè„šå°±ä¼šæ˜¾ç¤º 'Â© 2018 - 2020'ï¼ˆ2020 ä¸ºæœ€åä¸€æ¬¡é¡µé¢ç”Ÿæˆæ—¶é—´ï¼‰
  # å¦‚æœå°†æ­¤é¡¹ç•™ç©ºï¼Œåˆ™å•ç‹¬æ˜¾ç¤º 'Â© 2020'ï¼ˆ2020 ä¸ºæœ€åä¸€æ¬¡é¡µé¢ç”Ÿæˆæ—¶é—´ï¼‰
  # å¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºä»»ä½•å†…å®¹ï¼Œè¯·å°†æ­¤é¡¹è®¾ä¸º `false`
  copyright_since: 

  # ç½‘ç«™è®¡æ•°
  statistics: 

    # é€‰æ‹© LeanCloud/busuanzi ä¸ºç½‘ç«™è®¡æ•°ã€‚å¦‚æœä½ å®Œå…¨ä¸æƒ³å¯ç”¨ï¼Œå°† `use` é¡¹ç•™ç©ºå³å¯
    use:   # leancloud | busuanzi

    # å¦‚æœé€‰æ‹©ä½¿ç”¨ LeanCloudï¼Œåˆ™éœ€å®Œå–„ä¸‹é¢çš„é…ç½®é¡¹
    leancloud: 
      appId: 
      appKey: 
      serverURL:   # REST API æœåŠ¡å™¨åœ°å€ï¼ŒLeanCloud å›½é™…ç‰ˆä¸å¡«

    # å…¨ç«™ UVï¼ˆUnique Viewersï¼‰
    site_uv:
      enable: true
      before_text: '' # å±•ç¤ºåœ¨æ•°æ®å‰çš„å†…å®¹ï¼Œæ”¯æŒ HTML
      after_text: Viewers  # å±•ç¤ºåœ¨æ•°æ®åçš„å†…å®¹ï¼Œæ”¯æŒ HTML
      divider: '&nbsp;&nbsp;&nbsp;|' # åˆ†éš”ç¬¦ï¼ŒHTML è¯­æ³•æ”¯æŒ
    
    # å…¨ç«™ PVï¼ˆPage Viewsï¼‰
    site_pv:
      enable: true
      before_text: ''  # å±•ç¤ºåœ¨æ•°æ®å‰çš„å†…å®¹ï¼Œæ”¯æŒ HTML
      after_text: Views  # å±•ç¤ºåœ¨æ•°æ®åçš„å†…å®¹ï¼Œæ”¯æŒ HTML
      divider: ''  # åˆ†éš”ç¬¦ï¼ŒHTML è¯­æ³•æ”¯æŒ
    
    # é¡µé¢ PV
    page_pv:
      enable: true
      before_text: ''
      after_text: Views 

  # è‡ªå®šä¹‰é¡µè„šï¼Œæ”¯æŒ markdown
  custom_text: 
    # - ''
    # - ''



# ---------------------------------------------------------------
# ä¼˜åŒ–/åŠŸèƒ½ æ’ä»¶
# ---------------------------------------------------------------

# å›¾ç‰‡æ‡’åŠ è½½æ’ä»¶
lazyload:
  enable: false
  loadingImage: 

# ç«™å†…æœç´¢æ’ä»¶
search:
  enable: false
  path: search.json
  field: All  # Page | Post | All

# note æ ‡ç­¾æ’ä»¶
note: false

# fold å†…å®¹æŠ˜å æ’ä»¶
fold: 
  enable: true
  summary:   # é»˜è®¤æ‘˜è¦
  motion: 

# å›¾ç‰‡ç‚¹å‡»æ”¾å¤§æ’ä»¶
fancybox: 
  enable: false
  auto: false
  
# è¿”å›é¡¶éƒ¨
back_to_top: true

# æ·±è‰²æ¨¡å¼
darkmode: true



# ---------------------------------------------------------------
# CDN for vendors
# ---------------------------------------------------------------

# Vendors
# æŸä¸€é¡¹ç•™ç©ºåˆ™è°ƒç”¨ é»˜è®¤/æœ¬åœ° æ–‡ä»¶
vendors:

  # main style css
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2/dist/css/style/main.min.css
  # Version: 1.2
  # å¦‚æœä½ æœ‰è‡ªå®šä¹‰æ ·å¼ï¼Œè¯·åŠ¡å¿…å°†æ­¤é¡¹ä¿®æ”¹ä¸ºè‡ªå·±çš„ CDN åœ°å€ï¼Œæˆ–è€…å•çº¯ç•™ç©º
  style: 

  # darkmode
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2/dist/css/style/dark.min.css
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2/dist/js/darkmode.min.js
  # Version 1.2
  darkmode: 
    css: 
    js: 
  
  # code highlight css
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2/dist/css/highlight/
  # Version: 1.2
  highlight: 

  # highlight.js theme
  # https://cdn.jsdelivr.net/npm/highlight.js@10.1.2/styles/
  # Version: 10.1.2
  hljs: 

  # prism.js theme
  # https://cdn.jsdelivr.net/npm/prismjs@1.21.0/themes/
  # Version: 1.21.0
  prism: 

  # tag-plugin note css
  # https://github.com/ChrAlpha/hexo-theme-cards
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2/dist/css/style/note.min.css
  # Version 1.2
  note: 

  # Lazyload js
  # https://github.com/verlok/lazyload
  # Version: 17.1.2
  lazyload: 
  
  # back_to_top button
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2/dist/js/b2t.min.js
  # Version 1.2
  back_to_top: 

  # local search plugin
  # https://cdn.jsdelivr.net/npm/hexo-theme-cards@1.2/dist/js/local-search.min.js
  # Version 1.2
  local_search: 
  
  # Valine comments system
  # https://github.com/xcss/Valine/
  # Version: 1.4.14
  valine: 

  # MiniValine
  # https://github.com/MiniValine/MiniValine
  # Version 2.7.5
  minivaline: 

  # Artalk
  # https://github.com/qwqcode/Artalk
  # Version 1.0.6
  artalk: 
    css: 
    js: 
  
  # Wildfire comments system
  # https://github.com/cheng-kang/wildfire/
  # Version: 0.3.9
  wildfire: 
  
  # Twikoo
  # https://github.com/imaegoo/twikoo
  # Version 0.3.2
  twikoo: 

  # MathJax
  # https://www.mathjax.org/
  # Version: 3
  mathjax: 

  # KaTeX
  # https://katex.org/
  # Version 0.12.0
  katex: 
    css: 
    js: 

  # busuanzi counter js
  # https://busuanzi.ibruce.info
  busuanzi: 

  # Artitalk js
  # https://github.com/ArtitalkJS/Artitalk
  # Version: 3.1.2
  artitalk: 

  
  # jQuery js
  # https://github.com/jquery/jquery/
  # Version: 3.4.1
  jquery: 
  
  # fancybox css
  # https://github.com/fancyapps/fancybox/
  # Version: 3.5.7
  fancybox: 
    css: 
    js: 

  # è‡ªå®šä¹‰ script
  custom_script: 
    # - ''
    # - ''


